# Generated by Django 2.2.6 on 2019-11-08 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ISheet', '0003_auto_20191108_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_is',
            name='pd_FW',
        ),
        migrations.RemoveField(
            model_name='form_is',
            name='pd_Plat_methodology',
        ),
        migrations.RemoveField(
            model_name='form_is',
            name='pd_methodology',
        ),
    ]
