# Generated by Django 2.2.6 on 2019-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISheet', '0006_auto_20191108_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_is',
            name='pd_country',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
