# Generated by Django 2.2.6 on 2019-11-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISheet', '0008_auto_20191110_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_is',
            name='pd_country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
