# Generated by Django 2.2.6 on 2019-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISheet', '0009_auto_20191116_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_is',
            name='pd_Plat_methodology',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
